//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamCollectionApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>2096758176</string>
  <string>3022017447</string>
  <string>3018426177</string>
  <string>2491445658</string>
  <string>2066559813</string>
  <string>2635946959</string>
  <string>2066559813</string>
  <string>3018426177</string>
  <string>1167043224</string>
  <string>2189362870</string>
  <string>1767707642</string>
  <string>121225687</string>
  <string>852347216</string>
  <string>539525706</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Numbers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Numbers"]));
            }
            set {
                this["Numbers"] = value;
            }
        }
    }
}
